import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "../context/Context"; // Fix: import the correct provider
import { DeckContextProvider } from "@/context/DeckContext";
import NavBar from "./components/navBar"; // Import NavBar

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cmyk">
      <body>
        <UserContextProvider>
          <DeckContextProvider>
            <NavBar />
            {children}
          </DeckContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
