import type { Metadata } from "next";
import "./globals.css";
import { PropsProvider } from "../context/Context"; // Import the context provider
import NavBar from "./components/navBar"; // Import NavBar


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cmyk">
      <body>
        <PropsProvider>
          <NavBar/>
          {children}
        </PropsProvider>
      </body>
    </html>
  );
}
